language: node_js
node_js:
- '17'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: movieligent
  api_key:
    secure: ZxenHk0FDhGm2MA1I8RYTH3h+ufjrTgG7+iIAQ85Nsap4wYDRiCKTQH8G2QXMGXKSAu9nSvh8WcprawNGqzlresoE3Ntt2nSBPXe8T6rkt+OchyfFhYyX69jHMkqFwmJX7cYZa34uvip3ZrXEWPDpMVSDkalboLdrZiQUJYwaBzj4/DuNXNLARR3VKMKjeGq2gv/tA5Dx0gLoUHznxcWDBaJKdfZv5+2LDwoDEBX0jyknlH5D8ItAktfMf27gJ5EF7IkYT8T1UjNfVCfpy35L7WE77wTHIxhr0BnxohQ0dvfy+1kNhqDFHHDr5/1czdG6NisPsx7vyCBPxVUJnIbuoM5inp9N46kqAxhls0dFR2HZPAhf3vnb1jvgzO7lCpUxfS2niz9/rFZaQ+uzE391S2D38xAQHBsRHQELUyyrUpYeGkBW4PT9UNChrU4IXQXKuWJaxPuf2zZhWDqygOVRcurJDHDitiDcg5ylj8edtGrCJSWZ2vB6SxU8xsXqhshw3x9UxHcwIxAh/nuFlptCFWSTkyUwDwfpxX915VC51hKkNV/5FBX2nDFKvoEapJmkznWpNspsPxUtblNc4MUxdH+rNj0ZXidv7Tnu97R8iLYsB2YkEoncglwmdX0zFfkWpJiZ3I8E0UZ2nxcP6K1e+48P3JzBe8e+5aV4mwuz5I=
